name: app
description: "Una app para Re-Conectarte con tu eneagrama."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter

  # CÃ³digo de verificaciÃ³n
  http: ^1.6.0
  pinput: ^5.0.2

  # State management
  flutter_riverpod: ^2.5.1

  # Router
  go_router: ^14.1.0

  # -------------------------------
  # ğŸ”¥ Firebase (Versiones correctas)
  # -------------------------------
  firebase_core: ^3.8.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.4.2
  firebase_app_check: ^0.3.0+2

  # Google login
  google_sign_in: ^6.2.1

  flutter_signin_button: ^2.0.0

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
